-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_pi_cpapa.all.lua
-- Total length: 102

-- Sound: 4
sound.Add({
	name = "weap_cpapa_dryfire_plr",
	channel = CHAN_WPNFOLEY + 5,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/cpapa/weap_cpapa_dryfire_plr_01.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_02.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_03.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_04.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_05.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_06.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_ads_01.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_ads_02.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_ads_03.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_ads_04.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_ads_05.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_ads_06.ogg",
		}
})
-- Sound: 5
sound.Add({
	name = "weap_cpapa_dryfire1_plr",
	channel = CHAN_WPNFOLEY + 6,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/cpapa/weap_cpapa_dryfire_plr_01.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_02.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_03.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_04.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_05.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_06.ogg",
		}
})
-- Sound: 6
sound.Add({
	name = "weap_cpapa_dryfire2_plr",
	channel = CHAN_WPNFOLEY + 7,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/cpapa/weap_cpapa_dryfire_plr_01.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_02.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_03.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_04.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_05.ogg",
		"weapons/cpapa/weap_cpapa_dryfire_plr_06.ogg",
		}
})
-- Sound: 7
sound.Add({
	name = "weap_cpapa_fire_plr",
	channel = CHAN_WPNFOLEY + 8,
	level = 140,
	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/cpapa/weap_cpapa_fire_plr_01.ogg",
		}
})
-- Sound: 8
sound.Add({
	name = "weap_cpapa_fire_plr_atmo",
	channel = CHAN_WPNFOLEY + 9,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/atmo/exterior/pistol_mag/weap_pistol_mag_fire_plr_atmo_ext2_01.ogg",
		"weapons/atmo/exterior/pistol_mag/weap_pistol_mag_fire_plr_atmo_ext2_02.ogg",
		"weapons/atmo/exterior/pistol_mag/weap_pistol_mag_fire_plr_atmo_ext2_03.ogg",
		"weapons/atmo/exterior/pistol_mag/weap_pistol_mag_fire_plr_atmo_ext2_04.ogg",
		"weapons/atmo/exterior/pistol_mag/weap_pistol_mag_fire_plr_atmo_ext2_05.ogg",
		"weapons/atmo/exterior/pistol_mag/weap_pistol_mag_fire_plr_atmo_ext2_06.ogg",
		"weapons/atmo/interior/pistol/weap_pistol_fire_plr_atmo_int1_01.ogg",
		"weapons/atmo/interior/pistol/weap_pistol_fire_plr_atmo_int1_02.ogg",
		"weapons/atmo/interior/pistol/weap_pistol_fire_plr_atmo_int1_03.ogg",
		"weapons/atmo/interior/pistol/weap_pistol_fire_plr_atmo_int1_04.ogg",
		"weapons/atmo/interior/pistol/weap_pistol_fire_plr_atmo_int1_05.ogg",
		"weapons/atmo/interior/pistol/weap_pistol_fire_plr_atmo_int1_06.ogg",
		}
})
-- Sound: 9
sound.Add({
	name = "weap_cpapa_fire_plr_lfe",
	channel = CHAN_WPNFOLEY + 10,

	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/decho/weap_decho_fire_plr_lfe.ogg",
		"weapons/decho/weap_decho_fire_plr_lfe.ogg",
		}
})
-- Sound: 10
sound.Add({
	name = "weap_cpapa_fire_plr_mech",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/cpapa/weap_cpapa_fire_plr_mech_01.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_02.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_03.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_04.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_05.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_06.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_01.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_02.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_03.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_04.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_05.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_06.ogg",
		}
})
-- Sound: 11
sound.Add({
	name = "weap_cpapa_fire1_plr",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/cpapa/weap_cpapa_fire_plr_01.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_02.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_03.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_04.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_05.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_06.ogg",
		}
})
-- Sound: 12
sound.Add({
	name = "weap_cpapa_fire1_plr_atmo",
	channel = CHAN_WPNFOLEY + 3,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/atmo/exterior/pistol_mag/weap_pistol_mag_fire_plr_atmo_ext2_01.ogg",
		"weapons/atmo/exterior/pistol_mag/weap_pistol_mag_fire_plr_atmo_ext2_02.ogg",
		"weapons/atmo/exterior/pistol_mag/weap_pistol_mag_fire_plr_atmo_ext2_03.ogg",
		"weapons/atmo/exterior/pistol_mag/weap_pistol_mag_fire_plr_atmo_ext2_04.ogg",
		"weapons/atmo/exterior/pistol_mag/weap_pistol_mag_fire_plr_atmo_ext2_05.ogg",
		"weapons/atmo/exterior/pistol_mag/weap_pistol_mag_fire_plr_atmo_ext2_06.ogg",
		"weapons/atmo/interior/pistol/weap_pistol_fire_plr_atmo_int1_01.ogg",
		"weapons/atmo/interior/pistol/weap_pistol_fire_plr_atmo_int1_02.ogg",
		"weapons/atmo/interior/pistol/weap_pistol_fire_plr_atmo_int1_03.ogg",
		"weapons/atmo/interior/pistol/weap_pistol_fire_plr_atmo_int1_04.ogg",
		"weapons/atmo/interior/pistol/weap_pistol_fire_plr_atmo_int1_05.ogg",
		"weapons/atmo/interior/pistol/weap_pistol_fire_plr_atmo_int1_06.ogg",
		}
})
-- Sound: 13
sound.Add({
	name = "weap_cpapa_fire1_plr_lfe",
	channel = CHAN_WPNFOLEY + 4,

	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/decho/weap_decho_fire_plr_lfe.ogg",
		}
})
-- Sound: 14
sound.Add({
	name = "weap_cpapa_fire1_plr_mech",
	channel = CHAN_WPNFOLEY + 5,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/cpapa/weap_cpapa_fire_plr_mech_01.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_02.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_03.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_04.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_05.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_06.ogg",
		}
})
-- Sound: 15
sound.Add({
	name = "weap_cpapa_fire2_plr",
	channel = CHAN_WPNFOLEY + 6,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/cpapa/weap_cpapa_fire_plr_01.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_02.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_03.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_04.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_05.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_06.ogg",
		}
})
-- Sound: 16
sound.Add({
	name = "weap_cpapa_fire2_plr_atmo",
	channel = CHAN_WPNFOLEY + 7,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/atmo/exterior/pistol_mag/weap_pistol_mag_fire_plr_atmo_ext2_01.ogg",
		"weapons/atmo/exterior/pistol_mag/weap_pistol_mag_fire_plr_atmo_ext2_02.ogg",
		"weapons/atmo/exterior/pistol_mag/weap_pistol_mag_fire_plr_atmo_ext2_03.ogg",
		"weapons/atmo/exterior/pistol_mag/weap_pistol_mag_fire_plr_atmo_ext2_04.ogg",
		"weapons/atmo/exterior/pistol_mag/weap_pistol_mag_fire_plr_atmo_ext2_05.ogg",
		"weapons/atmo/exterior/pistol_mag/weap_pistol_mag_fire_plr_atmo_ext2_06.ogg",
		"weapons/atmo/interior/pistol/weap_pistol_fire_plr_atmo_int1_01.ogg",
		"weapons/atmo/interior/pistol/weap_pistol_fire_plr_atmo_int1_02.ogg",
		"weapons/atmo/interior/pistol/weap_pistol_fire_plr_atmo_int1_03.ogg",
		"weapons/atmo/interior/pistol/weap_pistol_fire_plr_atmo_int1_04.ogg",
		"weapons/atmo/interior/pistol/weap_pistol_fire_plr_atmo_int1_05.ogg",
		"weapons/atmo/interior/pistol/weap_pistol_fire_plr_atmo_int1_06.ogg",
		}
})
-- Sound: 17
sound.Add({
	name = "weap_cpapa_fire2_plr_lfe",
	channel = CHAN_WPNFOLEY + 8,

	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/decho/weap_decho_fire_plr_lfe.ogg",
		}
})
-- Sound: 18
sound.Add({
	name = "weap_cpapa_fire2_plr_mech",
	channel = CHAN_WPNFOLEY + 9,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/cpapa/weap_cpapa_fire_plr_mech_01.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_02.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_03.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_04.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_05.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_06.ogg",
		}
})
-- Sound: 19
sound.Add({
	name = "weap_cpapa_sup_plr",
	channel = CHAN_WPNFOLEY + 10,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/decho/weap_decho_sup_plr_01.ogg",
		"weapons/decho/weap_decho_sup_plr_02.ogg",
		"weapons/decho/weap_decho_sup_plr_03.ogg",
		"weapons/decho/weap_decho_sup_plr_04.ogg",
		"weapons/decho/weap_decho_sup_plr_05.ogg",
		"weapons/decho/weap_decho_sup_plr_06.ogg",
		}
})
-- Sound: 20
sound.Add({
	name = "weap_cpapa_sup_plr_atmo",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext1_01.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext1_02.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext1_03.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext1_04.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext1_05.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext1_06.ogg",
		"weapons/atmo/interior/dmr_sup/weap_dmr_sup_fire_plr_atmo_int1_01.ogg",
		"weapons/atmo/interior/dmr_sup/weap_dmr_sup_fire_plr_atmo_int1_02.ogg",
		"weapons/atmo/interior/dmr_sup/weap_dmr_sup_fire_plr_atmo_int1_03.ogg",
		"weapons/atmo/interior/dmr_sup/weap_dmr_sup_fire_plr_atmo_int1_04.ogg",
		"weapons/atmo/interior/dmr_sup/weap_dmr_sup_fire_plr_atmo_int1_05.ogg",
		"weapons/atmo/interior/dmr_sup/weap_dmr_sup_fire_plr_atmo_int1_06.ogg",
		}
})
-- Sound: 21
sound.Add({
	name = "weap_cpapa_sup_plr_lfe",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/decho/weap_decho_fire_plr_lfe.ogg",
		"weapons/decho/weap_decho_fire_plr_lfe.ogg",
		}
})
-- Sound: 22
sound.Add({
	name = "weap_cpapa_sup_plr_mech",
	channel = CHAN_WPNFOLEY + 3,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/cpapa/weap_cpapa_fire_plr_mech_01.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_02.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_03.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_04.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_05.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_06.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_01.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_02.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_03.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_04.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_05.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_06.ogg",
		}
})
-- Sound: 23
sound.Add({
	name = "weap_cpapa_sup1_plr",
	channel = CHAN_WPNFOLEY + 4,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/decho/weap_decho_sup_plr_01.ogg",
		"weapons/decho/weap_decho_sup_plr_02.ogg",
		"weapons/decho/weap_decho_sup_plr_03.ogg",
		"weapons/decho/weap_decho_sup_plr_04.ogg",
		"weapons/decho/weap_decho_sup_plr_05.ogg",
		"weapons/decho/weap_decho_sup_plr_06.ogg",
		}
})
-- Sound: 24
sound.Add({
	name = "weap_cpapa_sup1_plr_atmo",
	channel = CHAN_WPNFOLEY + 5,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext1_01.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext1_02.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext1_03.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext1_04.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext1_05.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext1_06.ogg",
		"weapons/atmo/interior/dmr_sup/weap_dmr_sup_fire_plr_atmo_int1_01.ogg",
		"weapons/atmo/interior/dmr_sup/weap_dmr_sup_fire_plr_atmo_int1_02.ogg",
		"weapons/atmo/interior/dmr_sup/weap_dmr_sup_fire_plr_atmo_int1_03.ogg",
		"weapons/atmo/interior/dmr_sup/weap_dmr_sup_fire_plr_atmo_int1_04.ogg",
		"weapons/atmo/interior/dmr_sup/weap_dmr_sup_fire_plr_atmo_int1_05.ogg",
		"weapons/atmo/interior/dmr_sup/weap_dmr_sup_fire_plr_atmo_int1_06.ogg",
		}
})
-- Sound: 25
sound.Add({
	name = "weap_cpapa_sup1_plr_lfe",
	channel = CHAN_WPNFOLEY + 6,

	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/decho/weap_decho_fire_plr_lfe.ogg",
		}
})
-- Sound: 26
sound.Add({
	name = "weap_cpapa_sup1_plr_mech",
	channel = CHAN_WPNFOLEY + 7,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/cpapa/weap_cpapa_fire_plr_mech_01.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_02.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_03.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_04.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_05.ogg",
		"weapons/cpapa/weap_cpapa_fire_plr_mech_06.ogg",
		}
})
-- Sound: 27
sound.Add({
	name = "weap_cpapa_sup2_plr",
	channel = CHAN_WPNFOLEY + 8,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/decho/weap_decho_sup_plr_01.ogg",
		"weapons/decho/weap_decho_sup_plr_02.ogg",
		"weapons/decho/weap_decho_sup_plr_03.ogg",
		"weapons/decho/weap_decho_sup_plr_04.ogg",
		"weapons/decho/weap_decho_sup_plr_05.ogg",
		"weapons/decho/weap_decho_sup_plr_06.ogg",
		}
})
-- Sound: 28
sound.Add({
	name = "weap_cpapa_sup2_plr_atmo",
	channel = CHAN_WPNFOLEY + 9,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext1_01.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext1_02.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext1_03.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext1_04.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext1_05.ogg",
		"weapons/atmo/exterior/dmr_sup/weap_dmr_sup_fire_plr_atmo_ext1_06.ogg",
		"weapons/atmo/interior/dmr_sup/weap_dmr_sup_fire_plr_atmo_int1_01.ogg",
		"weapons/atmo/interior/dmr_sup/weap_dmr_sup_fire_plr_atmo_int1_02.ogg",
		"weapons/atmo/interior/dmr_sup/weap_dmr_sup_fire_plr_atmo_int1_03.ogg",
		"weapons/atmo/interior/dmr_sup/weap_dmr_sup_fire_plr_atmo_int1_04.ogg",
		"weapons/atmo/interior/dmr_sup/weap_dmr_sup_fire_plr_atmo_int1_05.ogg",
		"weapons/atmo/interior/dmr_sup/weap_dmr_sup_fire_plr_atmo_int1_06.ogg",
		}
})
-- Sound: 29
sound.Add({
	name = "weap_cpapa_sup2_plr_lfe",
	channel = CHAN_WPNFOLEY + 10,

	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/decho/weap_decho_fire_plr_lfe.ogg",
		}
})
-- Sound: 30
sound.Add({
	name = "weap_cpapa_sup2_plr_mech",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {98,101},
	sound = {
		"weapons/cpapa/weap_cpapa_fire_plr_mech_01.ogg",
		}
})
-- Sound: 31
sound.Add({
	name = "weap_pi_cpapa_ads_down",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_ads_down.ogg",
		}
})
-- Sound: 32
sound.Add({
	name = "weap_pi_cpapa_ads_up",
	channel = CHAN_WPNFOLEY + 3,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_ads_up.ogg",
		}
})
-- Sound: 33
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_in_01",
	channel = CHAN_WPNFOLEY + 4,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_in_trigger_pull.ogg",
		}
})
-- Sound: 34
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_quick_drop_01",
	channel = CHAN_WPNFOLEY + 5,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_quick_drop.ogg",
		}
})

-- Sound: 35
sound.Add({
	name = "wfoly_plr_pi_cpapa_raise_01",
	channel = CHAN_WPNFOLEY + 6,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_raise.ogg",
		}
})

-- Sound: 35
sound.Add({
	name = "wfoly_plr_pi_cpapa_first_raise_01",
	channel = CHAN_WPNFOLEY + 6,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_first_raise_start.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_pi_cpapa_first_raise_02",
	channel = CHAN_WPNFOLEY + 7,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_first_raise_cylinderopen_01.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_pi_cpapa_first_raise_03",
	channel = CHAN_WPNFOLEY + 8,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_first_raise_cylinderclose_01.ogg",
		}
})
sound.Add({
	name = "wfoly_plr_pi_cpapa_first_raise_04",
	channel = CHAN_WPNFOLEY + 9,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_first_raise_end.ogg",
		}
})

-- Sound: 36
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_reload_01",
	channel = CHAN_WPNFOLEY + 7,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_cylinderopen_01_new.ogg",
		}
})
-- Sound: 37
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_reload_02",
	channel = CHAN_WPNFOLEY + 8,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_start.ogg",
		}
})
-- Sound: 38
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_reload_03",
	channel = CHAN_WPNFOLEY + 9,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_ejectorrod_01.ogg",
		}
})
-- Sound: 39
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_reload_04",
	channel = CHAN_WPNFOLEY + 10,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_shelleject_01.ogg",
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_shelleject_02.ogg",
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_shelleject_03.ogg",
		}
})
-- Sound: 40
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_reload_05",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_arm.ogg",
		}
})
-- Sound: 41
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_reload_06",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_speedloader_01.ogg",
		}
})
-- Sound: 42
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_reload_07",
	channel = CHAN_WPNFOLEY + 3,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_shake.ogg",
		}
})
-- Sound: 43
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_reload_08",
	channel = CHAN_WPNFOLEY + 4,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_cylinderclose_01.ogg",
		}
})
-- Sound: 44
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_reload_09",
	channel = CHAN_WPNFOLEY + 5,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_end.ogg",
		}
})
-- Sound: 45
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_reload_fast_01",
	channel = CHAN_WPNFOLEY + 6,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_fast_start.ogg",
		}
})
-- Sound: 46
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_reload_fast_02",
	channel = CHAN_WPNFOLEY + 7,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_fast_cyclinderopen_01.ogg",
		}
})
-- Sound: 47
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_reload_fast_03",
	channel = CHAN_WPNFOLEY + 8,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_fast_ejectorrod_01.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_reload_fast_04",
	channel = CHAN_WPNFOLEY + 9,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_fast_shelleject_01.ogg",
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_fast_shelleject_02.ogg",
		}
})
-- Sound: 49
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_reload_fast_05",
	channel = CHAN_WPNFOLEY + 10,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_fast_shelleject_03.ogg",
		}
})
-- Sound: 50
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_reload_fast_06",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_fast_arm.ogg",
		}
})
-- Sound: 51
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_reload_fast_07",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_fast_speedloader_01.ogg",
		}
})
-- Sound: 52
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_reload_fast_08",
	channel = CHAN_WPNFOLEY + 3,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_fast_grip.ogg",
		}
})
-- Sound: 53
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_reload_fast_09",
	channel = CHAN_WPNFOLEY + 4,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_fast_cylinderclose_01.ogg",
		}
})
-- Sound: 54
sound.Add({
	name = "wfoly_plr_pi_cpapa_charge_reload_fast_10",
	channel = CHAN_WPNFOLEY + 5,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_charge_reload_fast_end.ogg",
		}
})
-- Sound: 55
sound.Add({
	name = "wfoly_plr_pi_cpapa_drop_01",
	channel = CHAN_WPNFOLEY + 6,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_drop.ogg",
		}
})
-- Sound: 56
sound.Add({
	name = "wfoly_plr_pi_cpapa_fire_last_01",
	channel = CHAN_WPNFOLEY + 7,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_fire_last.ogg",
		}
})
-- Sound: 57
sound.Add({
	name = "wfoly_plr_pi_cpapa_fire_target_01",
	channel = CHAN_WPNFOLEY + 8,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_fire_target.ogg",
		}
})
-- Sound: 58
sound.Add({
	name = "wfoly_plr_pi_cpapa_inspect_01",
	channel = CHAN_WPNFOLEY + 9,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_inspect_01.ogg",
		}
})
-- Sound: 59
sound.Add({
	name = "wfoly_plr_pi_cpapa_inspect_02",
	channel = CHAN_WPNFOLEY + 10,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_inspect_02.ogg",
		}
})
-- Sound: 60
sound.Add({
	name = "wfoly_plr_pi_cpapa_inspect_03",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_inspect_03.ogg",
		}
})
-- Sound: 61
sound.Add({
	name = "wfoly_plr_pi_cpapa_inspect_04",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_inspect_04.ogg",
		}
})
-- Sound: 62
sound.Add({
	name = "wfoly_plr_pi_cpapa_melee_hit_01_01",
	channel = CHAN_WPNFOLEY + 3,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_melee_hit_01.ogg",
		}
})
-- Sound: 63
sound.Add({
	name = "wfoly_plr_pi_cpapa_melee_hit_02_01",
	channel = CHAN_WPNFOLEY + 4,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_melee_hit_02.ogg",
		}
})
-- Sound: 64
sound.Add({
	name = "wfoly_plr_pi_cpapa_stock_reload_01",
	channel = CHAN_WPNFOLEY + 5,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_start.ogg",
		}
})
-- Sound: 65
sound.Add({
	name = "wfoly_plr_pi_cpapa_stock_reload_02",
	channel = CHAN_WPNFOLEY + 6,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_cylinderopen_01.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "wfoly_plr_pi_cpapa_stock_reload_03",
	channel = CHAN_WPNFOLEY + 7,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_ejectorrod_01.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "wfoly_plr_pi_cpapa_stock_reload_04",
	channel = CHAN_WPNFOLEY + 8,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_shelleject_01.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_pi_cpapa_stock_reload_05",
	channel = CHAN_WPNFOLEY + 9,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_shelleject_02.ogg",
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_shelleject_03.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_pi_cpapa_stock_reload_06",
	channel = CHAN_WPNFOLEY + 10,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_arm.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_pi_cpapa_stock_reload_07",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_speedloader_01.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_pi_cpapa_stock_reload_08",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_rattle.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_pi_cpapa_stock_reload_09",
	channel = CHAN_WPNFOLEY + 3,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_cylinderclose_01.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_pi_cpapa_stock_reload_10",
	channel = CHAN_WPNFOLEY + 4,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_end.ogg",
		}
})
-- Sound: 74
sound.Add({
	name = "wfoly_plr_pi_cpapa_stock_reload_fast_01",
	channel = CHAN_WPNFOLEY + 5,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_fast_cylinderopen_01.ogg",
		}
})
-- Sound: 75
sound.Add({
	name = "wfoly_plr_pi_cpapa_stock_reload_fast_02",
	channel = CHAN_WPNFOLEY + 6,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_fast_start.ogg",
		}
})
-- Sound: 76
sound.Add({
	name = "wfoly_plr_pi_cpapa_stock_reload_fast_03",
	channel = CHAN_WPNFOLEY + 7,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_fast_ejectorrod_01.ogg",
		}
})
-- Sound: 77
sound.Add({
	name = "wfoly_plr_pi_cpapa_stock_reload_fast_04",
	channel = CHAN_WPNFOLEY + 8,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_fast_shelleject_01.ogg",
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_fast_shelleject_02.ogg",
		}
})
-- Sound: 78
sound.Add({
	name = "wfoly_plr_pi_cpapa_stock_reload_fast_05",
	channel = CHAN_WPNFOLEY + 9,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_fast_shelleject_03.ogg",
		}
})
-- Sound: 79
sound.Add({
	name = "wfoly_plr_pi_cpapa_stock_reload_fast_06",
	channel = CHAN_WPNFOLEY + 10,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_fast_grab.ogg",
		}
})
-- Sound: 80
sound.Add({
	name = "wfoly_plr_pi_cpapa_stock_reload_fast_07",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_fast_speedloader_01.ogg",
		}
})
-- Sound: 81
sound.Add({
	name = "wfoly_plr_pi_cpapa_stock_reload_fast_08",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_fast_cylinderclose_01.ogg",
		}
})
-- Sound: 82
sound.Add({
	name = "wfoly_plr_pi_cpapa_stock_reload_fast_09",
	channel = CHAN_WPNFOLEY + 3,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_pi_cpapa_stock_reload_fast_end_old.ogg",
		}
})
-- Sound: 83
sound.Add({
	name = "wfoly_plr_pi_cpapa_stp_sp_empty_drop_01",
	channel = CHAN_WPNFOLEY + 4,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_plr_pi_cpapa_stp_sp_empty_drop_down.ogg",
		}
})
-- Sound: 84
sound.Add({
	name = "wfoly_plr_pi_cpapa_stp_sp_empty_raise_01",
	channel = CHAN_WPNFOLEY + 5,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_plr_pi_cpapa_stp_sp_empty_raise_up.ogg",
		}
})
-- Sound: 85
sound.Add({
	name = "wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_01",
	channel = CHAN_WPNFOLEY + 6,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_cylinderopen_01.ogg",
		}
})
-- Sound: 86
sound.Add({
	name = "wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_02",
	channel = CHAN_WPNFOLEY + 7,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_start.ogg",
		}
})
-- Sound: 87
sound.Add({
	name = "wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_03",
	channel = CHAN_WPNFOLEY + 8,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_leftarm.ogg",
		}
})
-- Sound: 88
sound.Add({
	name = "wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_04",
	channel = CHAN_WPNFOLEY + 9,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_load1stshell_01.ogg",
		}
})
-- Sound: 89
sound.Add({
	name = "wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_05",
	channel = CHAN_WPNFOLEY + 10,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_grab2ndshell.ogg",
		}
})
-- Sound: 90
sound.Add({
	name = "wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_06",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_load2ndtshell_01.ogg",
		}
})
-- Sound: 91
sound.Add({
	name = "wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_07",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_grab3rdshell.ogg",
		}
})
-- Sound: 92
sound.Add({
	name = "wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_08",
	channel = CHAN_WPNFOLEY + 3,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_load3rdtshell_01.ogg",
		}
})
-- Sound: 93
sound.Add({
	name = "wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_09",
	channel = CHAN_WPNFOLEY + 4,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_grab4thshell.ogg",
		}
})
-- Sound: 94
sound.Add({
	name = "wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_10",
	channel = CHAN_WPNFOLEY + 5,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_load4thshell_01.ogg",
		}
})
-- Sound: 95
sound.Add({
	name = "wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_11",
	channel = CHAN_WPNFOLEY + 6,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_grab5thshell.ogg",
		}
})
-- Sound: 96
sound.Add({
	name = "wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_12",
	channel = CHAN_WPNFOLEY + 7,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_load5thshell_01.ogg",
		}
})
-- Sound: 97
sound.Add({
	name = "wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_13",
	channel = CHAN_WPNFOLEY + 8,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_grab6thshell.ogg",
		}
})
-- Sound: 98
sound.Add({
	name = "wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_14",
	channel = CHAN_WPNFOLEY + 9,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_load6thshell_01.ogg",
		}
})
-- Sound: 99
sound.Add({
	name = "wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_15",
	channel = CHAN_WPNFOLEY + 10,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_armdown.ogg",
		}
})
-- Sound: 100
sound.Add({
	name = "wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_16",
	channel = CHAN_WPNFOLEY + 1,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_cylinderclose_01.ogg",
		}
})
-- Sound: 101
sound.Add({
	name = "wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_17",
	channel = CHAN_WPNFOLEY + 2,

	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_cpapa/wfoly_plr_pi_cpapa_stp_sp_loaded_first_raise_end.ogg",
		}
})
